MySQL_TryFix/MySQL_TryFix/urls.py
from django.contrib import admin
from django.urls import path, include

from card_app.views import doctor_personal_data_review, patient_personal_data_review, pharmacist_personal_data_review, \
    doctor_new_consultation, doctor_new_prescription

"""importexport URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
from django.contrib import admin
from django.urls import path
from projectapp import views
"""

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('card_app.urls')),
    # path('upload', views.simple_upload(request)),  # youtube / pe gitgub este "path('', views.simple_upload),"
    path('users/', include('django.contrib.auth.urls')),  # for setting up authentication view

    path('drpdr', doctor_personal_data_review),  # NEW (replacing: 'doctor_detail_view')
    path('papdr', patient_personal_data_review),  # NEW
    path('phpdr', pharmacist_personal_data_review),  # NEW
    path('drnewc', doctor_new_consultation),  # NEW
    path('drnewp', doctor_new_prescription),  # NEW
]

MySQL_TryFix/card_app/urls.py
from django.urls import path

from card_app import views

urlpatterns = [
    # DOCTOR related urls :
    # path('doctor_login', views.doctor_login, name='doctor_login'),
    path('doctor_registration', views.doctor_registration, name='doctor_registration'),
    path('doctor_patient_search', views.doctor_patient_search, name='doctor_patient_search'),
    # path('doctor_prescription_by_SSN_review', views.doctor_prescription_by_SSN_review, name='doctor_prescription_by_SSN_review'),
    path('doctor_all_prescriptions_review', views.doctor_all_prescriptions_review, name='doctor_all_prescriptions_review'),
    path('doctor_all_consultations_review', views.doctor_all_consultations_review, name='doctor_all_consultations_review'),
    path('doctor_new_consultation', views.doctor_new_consultation, name='doctor_new_consultation'),
    path('doctor_new_prescription', views.doctor_new_prescription, name='doctor_new_prescription'),
    # path('user_create_view', views.user_create_view, name='user_create_view'),  # NEW
    # path('doctor_create_view', views.doctor_create_view, name='doctor_create_view'),  # NEW
    path('doctor_personal_data_review', views.doctor_personal_data_review, name='doctor_personal_data_review'),  # NEW

    # PATIENT related urls :
    # path('patient_login', views.patient_login, name='patient_login'),
    # path('patient_login_var-curs', views.patient_login, name='patient_login_var-curs'),
    path('patient_registration', views.patient_registration, name='patient_registration'),
    path('patient_personal_data_review', views.patient_personal_data_review, name='patient_personal_data_review'),

    # PHARMACIST related urls :
    # path('pharmacist_login', views.pharmacist_login, name='pharmacist_login'),
    # path('pharmacist_patient_search', views.pharmacist_patient_search, name='pharmacist_patient_search'),
    path('pharmacist_registration', views.pharmacist_registration, name='pharmacist_registration'),
    path('pharmacist_personal_data_review', views.pharmacist_personal_data_review,
         name='pharmacist_personal_data_review'),
    # path('pharmacist_prescription_search', views.pharmacist_prescription_search, name='pharmacist_prescription_search'),
    path('pharmacist_all_prescriptions_review', views.pharmacist_all_prescriptions_review, name='pharmacist_all_prescriptions_review'),


    # HOME url :
    path('', views.virtual_health_card, name='virtual_health_card'),

    # AUTHENTICATION related urls :
    # path('login', views.login_common, name='login'),
    # path('logged_out', views.logged_out, name='logged_out'),
    path('password_reset_form', views.password_reset_form, name='password_reset_form'),
    path('password_reset_email', views.password_reset_email, name='password_reset_email'),
    path('password_reset_confirm', views.password_reset_confirm, name='password_reset_confirm'),
    path('password_reset_complete', views.password_reset_complete, name='password_reset_complete'),
    path('password_reset_done', views.password_reset_done, name='password_reset_done'),
    path('login_redirect', views.login_redirect, name='login_redirect'),

]



MySQL_TryFix/card_app/models.py
# blank=True,  # TODO: trebuie sa avem aceasta mentiune sau NU :
# blank determines whether the field will be required in forms. This includes the admin and your custom forms.
# If blank=True , then the field will not be required, whereas if it's False the field cannot be blank.

# null=True,  # TODO: trebuie sa avem aceasta mentiune sau NU :
# null=True sets NULL (versus NOT NULL) on the column in your DB.
# Blank values for Django field types such as DateTimeField or ForeignKey will be stored as NULL in the DB.
# https://stackoverflow.com/questions/8609192/differentiate-null-true-blank-true-in-django
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class CommonModel(models.Model):                                    # NEW 04.DEC
    created_at = models.DateField(default=timezone.now)  # ?? sau (auto_now_add=True) ??
    updated_at = models.DateField(default=timezone.now)  # ?? sau (auto_now=True) ??
    # hitrate = models.IntegerField(default=0)

    class Meta:
        abstract = True


class Patient(CommonModel):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
    )
    ssn = models.IntegerField()
    date_of_birth = models.DateField(null=True, blank=True)  # TODO: trebuie 'null=True, blank=True' ??
    # It seems that django's DateField is accepting strings as a default. Try converting your datetime field like this:
    # YourModel.date_of_birth = your_csv_dict['completion_date'].strftime("%Y-%d-%m")      # NEW 08.DEC
    citizenship = models.TextField()
    phone_nr = models.TextField()
    residence = models.ForeignKey(  # One-To-Many relation to Residences table
        'Residence',
        on_delete=models.DO_NOTHING,
    )
    insurance = models.ForeignKey(  # One-To-Many relation to Insurances table
        'Insurance',
        on_delete=models.DO_NOTHING,
    )
    doctor = models.ForeignKey(  # The field 'doctor' clashes with the field 'doctor' from model 'card_app.commonmodel'.
        'Doctor',
        on_delete=models.DO_NOTHING,
    )

    def __str__(self):
        return str(self.id) + ". " + self.user.first_name + " " + self.user.last_name + " (" + self.residence.name + ")"

    class Meta:
        ordering = ('id',)


class Residence(models.Model):
    name = models.TextField()

    def __str__(self):
        return str(self.id) + ". " + self.name

    class Meta:
        ordering = ('id',)


class Doctor(CommonModel):  # class Doctor(CommonModel, models.Model)
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
    )
    authorisation = models.IntegerField()     # CharField(max_length=5)
    doctor_type = models.ForeignKey(
        'DoctorType',
        on_delete=models.DO_NOTHING,
    )
    speciality = models.ForeignKey(
        'Speciality',
        on_delete=models.DO_NOTHING,
    )
    clinic = models.ForeignKey(
        'Clinic',
        null=True,             # NEW 07.DEC - nu mergea importul in BD
        blank=True,             # NEW 07.DEC - nu mergea importul in BD
        on_delete=models.DO_NOTHING,
    )
    clinic_type = models.ForeignKey(
        'ClinicType',
        null=True,             # NEW 07.DEC - nu mergea importul in BD
        blank=True,             # NEW 07.DEC - nu mergea importul in BD
        on_delete=models.DO_NOTHING,
    )

    def __str__(self):
        return str(self.id) + ". " + self.user.first_name + " " + self.user.last_name
               # + \
               # " (" + self.clinic.name + "--" + self.clinic_type.clinic_type + "--" + self.speciality.name + ")"

    class Meta:
        ordering = ('id',)


class DoctorType(models.Model):
    doctor_type = models.TextField()

    def __str__(self):
        return str(self.id) + ". " + self.doctor_type

    class Meta:
        ordering = ('id',)


class Pharmacist(CommonModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    authorisation = models.CharField(max_length=6)
    pharmacy = models.ForeignKey(
        'Pharmacy',
        on_delete=models.DO_NOTHING,
    )

    def __str__(self):
        return str(self.id) + ". " + self.user.first_name + " " + self.user.last_name + " (" + self.pharmacy.name + ")"

    class Meta:
        ordering = ('id',)


class Speciality(models.Model):
    name = models.TextField()

    def __str__(self):
        return str(self.id) + ". " + self.name

    class Meta:
        ordering = ('id',)


class DiagnosticType(models.Model):
    diag_type = models.TextField()

    def __str__(self):
        return str(self.id) + ". " + self.diag_type

    class Meta:
        ordering = ('id',)


class Clinic(models.Model):
    name = models.TextField(
    )

    def __str__(self):
        return str(self.id) + ". " + self.name

    class Meta:
        ordering = ('id',)


class ClinicType(models.Model):
    clinic_type = models.TextField()

    def __str__(self):
        return str(self.id) + ". " + self.clinic_type

    class Meta:
        ordering = ('id',)


class Consultation(CommonModel):
    patient = models.ForeignKey(  # The field 'patient' clashes with the field 'patient' from model 'card_app.commonmodel'.
        'Patient',
        on_delete=models.CASCADE
    )
    diagnostic_type = models.ForeignKey(
        'DiagnosticType',
        on_delete=models.DO_NOTHING,
    )
    medical_report = models.TextField()

    doctor = models.ForeignKey(  # The field 'doctor' clashes with the field 'doctor' from model 'card_app.commonmodel'.
        'Doctor',
        on_delete=models.DO_NOTHING,
    )
    clinic = models.ForeignKey(
        'Clinic',
        on_delete=models.DO_NOTHING,
    )
    clinic_type = models.ForeignKey(
        'ClinicType',
        on_delete=models.DO_NOTHING,
    )
    insurance = models.ForeignKey(
        'Insurance',
        on_delete=models.DO_NOTHING,
    )

    def __str__(self):
        return str(self.id) + ". " + str(self.created_at) + " - " + self.patient.user.first_name + " " + \
               self.patient.user.last_name + " - " + " (" + str(self.clinic) + " - " + \
               self.doctor.speciality.name + ")"
        # when concatenate, all the fields are taking the type of the first(this is why is mentioned str(self.date) )
        # since there is no doctor speciality in Consultations, this is imported from Doctors table: doctor.speciality,
        # si apoi facem legatura cu tabela Speciality, ca sa luam numele specialitatii: doctor.speciality.name

        # return str(self.id) + ". " + str(self.creation_date) + " - " + self.medical_report  # NEW
    class Meta:
        ordering = ('id',)


class PrescriptionType(models.Model):
    diagnostic_code = models.CharField(max_length=10)
    prescription_type = models.TextField()

    def __str__(self):
        return str(self.id) + ". " + self.diagnostic_code + " / " + self.prescription_type

    class Meta:
        ordering = ('id',)


class ActiveSubstance(models.Model):
    active_substance = models.TextField()

    def __str__(self):
        return str(self.id) + ". " + self.active_substance

    class Meta:
        ordering = ('id',)


class PharmaceuticalForm(models.Model):
    pharmaceutical_form = models.TextField()

    def __str__(self):
        return str(self.id) + ". " + self.pharmaceutical_form

    class Meta:
        ordering = ('id',)


class Concentration(models.Model):
    concentration = models.TextField()

    def __str__(self):
        return str(self.id) + ". " + str(self.concentration)

    class Meta:
        ordering = ('id',)


class Prescription(CommonModel):
    series = models.CharField(max_length=3, primary_key=True)  # NEW: 15.DEC

    number = models.CharField(max_length=6, default=uuid.uuid4, unique=True)  # NEW: 15.DEC

    active_substance = models.ForeignKey(   # One-To-Many relation to ActiveSubstance table
        'ActiveSubstance',
        on_delete=models.DO_NOTHING,
    )
    pharmaceutical_form = models.ForeignKey(  # One-To-Many relation to PharmaceuticalForm table
        'PharmaceuticalForm',
        on_delete=models.DO_NOTHING,
    )
    concentration = models.ForeignKey(      # One-To-Many relation to Concentration table
        'Concentration',
        on_delete=models.DO_NOTHING,
    )
    consultation = models.ForeignKey(  # The field 'consultation' clashes with the field 'consultation' from model 'card_app.commonmodel'.
        'Consultation',
        on_delete=models.DO_NOTHING,
    )
    prescription_type = models.ForeignKey(  # One-To-Many relation to PrescriptionType table  # dublare cu linia 241
        'PrescriptionType',
        on_delete=models.DO_NOTHING,
    )
    doctor = models.ForeignKey(  # The field 'doctor' clashes with the field 'doctor' from model 'card_app.commonmodel'.
        'Doctor',
        on_delete=models.DO_NOTHING,
    )
    patient = models.ForeignKey(  # The field 'patient' clashes with the field 'patient' from model 'card_app.commonmodel'.
        'Patient',
        on_delete=models.DO_NOTHING,
    )
    insurance = models.ForeignKey(      # One-To-Many relation to Insurance table
        'Insurance',
        on_delete=models.DO_NOTHING,
    )
    # updated_at = models.AutoDateTimeField()  # NEW/01.DEC.2020                            # commented on 08.DEC
    # # AutoDateTimeField() takes no arguments: "updated_at = models.AutoDateTimeField(default=timezone.now)"

    def __str__(self):
        return str(self.id) + ". " + self.doctor.user.first_name + " " + self.doctor.user.last_name + \
               " " + self.doctor.speciality.name + " (Picked-up by " + \
               self.patient.user.first_name + " " + self.patient.user.last_name + ")"

    class Meta:
        ordering = ('id',)


class PrescriptionPickUp(CommonModel):
    pharmacist = models.ForeignKey(  # The field 'pharmacist' clashes with the field 'pharmacist' from model 'card_app.commonmodel'.
        'Pharmacist',
        on_delete=models.DO_NOTHING,
    )

MySQL_TryFix/templates/doctor/OLD_doctor_new_consultation_prescription_common.html
{# doctor_new_consultation_prescription_common #}

{% block content %}
{#    <div class="user_new">#}
{#        <h4> {{ sub_title_1 }} </h4>#}
        <form action="" method="post">
{##}
{#            {% csrf_token %}#}

        <label for="first_name">Patient's First Name</label>
        <select id="first_name" class="buttons" type="text" placeholder="Patient's First Name" name="first_name" required>
            {% for patient in patients %}
                <option value="{{ patient.id }}">{{ patient.user.first_name }}</option>
            {% endfor %}
        </select>
        <br/><br/>

        <label for="last_name">Patient's Last Name</label>
        <select id="last_name" class="buttons" type="text" placeholder="Patient's Last Name" name="last_name" required>
            {% for patient in patients %}
                <option value="{{ patient.id }}">{{ patient.user.last_name }}</option>
            {% endfor %}
        </select>
        <br/><br/>

        </form>
{#    </div>#}
{% endblock %}

MySQL_TryFix/templates/doctor/doctor_all_consultations_review.html
{# doctor_all_consultations_review #}

{% extends 'base_doctor_to_consultation.html' %}

{% block content %}
    {% if user.is_authenticated %}

    <form action="" method="post">
        {% csrf_token %}

        <label for="ssn">
            <h2 style="text-align:center">Search PATIENT's CONSULTATION(S) =
                <input type="text" id="myInput" onkeyup="mySSNFunction()" placeholder="Search by SSN (13 digits)"
                       title="Type in a SSN number (13 digits only)">
            </h2>
        </label>
    </form>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="/static/src/tablesort.css">  {# type="text/css" #}

    <table class="table-sortable" border="1" id="myTable">
        <tr class="header">
            <th>Patient's<br>SSN</th>
            <th>Date &<br>Time</th>
            <th>Clinic's Name<br>(& Type)</th>
            <th>Doctor's<br>Full Name</th>
            <th>Patient's<br>Full Name</th>
            <th>Diagnostic<br>Type</th>
            <th>Medical Report</th>
        </tr>

        {% for consultation in consultations %}
            <tr>
                <td>{{ consultation.patient.ssn }}</td>
                <td>{{ consultation.created_at }}</td>
                <td>{{ consultation.clinic.name }} ({{ consultation.clinic_type.clinic_type }})</td>
                <td>{{ consultation.doctor.user.last_name }} {{ consultation.doctor.user.first_name }}</td>
                <td>{{ consultation.patient.user.last_name }} {{ consultation.patient.user.first_name }}</td>
                <td>{{ consultation.diagnostic_type.diag_type }}</td>
                <td>{{ consultation.medical_report }}</td>
            </tr>
        {% endfor %}
    </table>
    <script type="text/javascript" src="/static/src/tablesort.js"></script>
    <br>

    <div>
        <a href="{% url 'doctor_new_consultation' %}">Create a NEW CONSULTATION</a>
    </div>

    <script>
        function mySSNFunction() {
            var input, filter, table, tr, td, i, txtValue;  {# 'var' used instead of 'let' or 'const' #}
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");

            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                        }
                }
            }
        }
    </script>

    <p>
        {% if object.user != None and object.user != '' %}
            {% else %} The USER you are looking for is not yet created . . .
        {% endif %}
    </p>
    <br>  <br/>

    {% else %}
        <h1>PLEASE AUTHENTICATE as a DOCTOR to be able to access this page . . . </h1>
    {% endif %}

{% endblock %}

MySQL_TryFix/templates/doctor/doctor_all_prescriptions_review.html
{# doctor_all_prescriptions_review #}

{% extends 'base_doctor_to_prescription.html' %}

{% block content %}
    {% if user.is_authenticated %}

    <title>{{ page_title }}</title>
    <form action="" method="post">
        {% csrf_token %}

        <label for="ssn">
            <h2 style="text-align:center">Search PATIENT's PRESCRIPTION(S) =
                <input type="text" id="myInput" onkeyup="mySSNFunction()" placeholder="Search by SSN . . ."
                       title="Type in a SSN number (13 digits only)">
            </h2>
        </label>

    </form>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        * {
            box-sizing: border-box;
        }

        #myInput {
            background-image: url('/static/searchicon_small.jpg');
            background-position: 10px 10px;
            background-repeat: no-repeat;
            {#width: 100%;#}
            font-size: 32px;
            padding: 12px 20px 12px 40px;
            border: 1px solid #ddd;
            margin-bottom: 12px;
        }

        #myTable {
            border-collapse: collapse;
            width: 100%;
            border: 1px solid #ddd;
            font-size: 18px;
        }

        #myTable th, #myTable td {
            text-align: left;
            padding: 12px;
        }

        #myTable tr {
            border-bottom: 1px solid #ddd;
        }

        #myTable tr.header, #myTable tr:hover {
            background-color: #f1f1f1;
        }
    </style>

    <table border="1" id="myTable">
          <tr class="header">
              <th>Patient's<br>SSN</th>
              <th>Date&<br>Time</th>
              <th>Doctor's<br>Full Name</th>
              <th>Patient's<br>Full Name</th>
              <th>Series&<br>Number</th>
              <th>Diagnostic<br>Code</th>
              <th>Diagnostic<br>Type</th>
              <th>Insurance</th>
              <th>Active<br>Substance</th>
              <th>Drug Ph.Form</th>
              <th>Conc.</th>
              <th>Picked-up?</th>
            </tr>

        {% for prescription in prescriptions %}
            <tr>
                <td>{{ prescription.patient.ssn }}</td>
                <td>{{ prescription.created_at }}</td>
                <td>{{ prescription.doctor.user.last_name }} {{ prescription.doctor.user.first_name }}</td>
                <td>{{ prescription.patient.user.last_name }} {{ prescription.patient.user.first_name }}</td>
                <td>{{ prescription.series }} {{ prescription.number }}</td>
                <td>{{ prescription.prescription_type.diagnostic_code }}</td>
                <td>{{ prescription.consultation.diagnostic_type.diag_type }}</td>
                <td>{{ prescription.patient.insurance.name }}</td>
                <td>{{ prescription.active_substance.active_substance }}</td>
                <td>{{ prescription.pharmaceutical_form.pharmaceutical_form }}</td>
                <td>{{ prescription.concentration.concentration }}</td>
                <td>{{ prescription.patient.prescriptionpickup.pharmacy.name}}</td>    {# NU SCOATE NIMIC . . #}
            </tr>
        {% endfor %}
    </table>
    <br>

    <div>
        <a href="{% url 'doctor_new_prescription' %}">Create a NEW PRESCRIPTION</a>
    </div>

    <script>
        function mySSNFunction() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");

            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                        }
                }
            }
        }
    </script>

    <p>
        {% if object.user != None and object.user != '' %}
            {% else %}The USER you are looking for is not yet created . . .
        {% endif %}
    </p>
    <br>  <br/>

    {% else %}
        <h1>PLEASE AUTHENTICATE as a DOCTOR to be able to access this page . . . </h1>
    {% endif %}

{% endblock %}

MySQL_TryFix/templates/doctor/doctor_patient_search.html
{# doctor_patient_search #}

<!DOCTYPE html>
{% extends 'base_doctor.html' %}
{% load static %}
{% block errors %}
    <title>{{ page_title }}</title>
    <h3> {{ main_title }} </h3>
{% endblock %}

{% block content %}
    <body>
    {# TODO: fiecare dintre aceste trei campuri trebuie sa fie de tip SELECT/SEARCH :   #}
    <div class="user_new">
        <h4> Please fill-in data for at least one of the fields, and then press the SEARCH button: </h4>

        <label for="prenume">First name</label>
        <label>
            <input class="buttons" type="text" placeholder="First name" name="pa_f_name" required>
        </label>
        <br> <br>

        <label for="nume">Last name</label>
        <label>
            <input class="buttons" type="text" placeholder="Last name" name=pa_l_name" required>
        </label>
        <br> <br>

        <label for="ssn">SSN</label>
        <label>
            <input class="buttons" type="text" placeholder="SSN" name=pa_ssn" required>
        </label> {# TODO: care este necesitatea fiecaruia dintre aceste informatii : placeholder, name ?? " #}
        <br> <br>
    </div>

    <br>
    <button class="favorite styled" type="button" id="search_PA" onclick="myFunction()">SEARCH</button>
    {# TODO: la apasaerea butonului "SEARCH" , sa extragem in tabelului de mai jos clientul/clientii cu match" #}
    <script>
        function myFunction() {
            var x = document.getElementById("search_PA");
            x.disabled = true;
        }
    </script>
    <br> <br>

    {# TODO: AICI TREBUIE sa apara rezultatul SEARCH-ului de mai sus :  #}
    {% for patient in patients %}
        {{ patient.first_name }} {{ patient.last_name }}
    {% endfor patient %}

{% endblock %}

MySQL_TryFix/templates/doctor/doctor_prescription_review_salvat_09DEC2020.html
{# doctor_prescription_review #}

{% extends 'base_doctor_to_prescription.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {#            DOCTOR's PRESCRIPTION Detailed Data Review for PATIENT (SSN) = {{ object.patient.ssn }} #}
        <label for="ssn">
            <h2 style="text-align:center">PRESCRIPTION(S) Search by PATIENT(SSN) =
                <input style="class: center" id="ssn" class="buttons" type="text" placeholder="0000000000000" name="ssn" required>
            </h2>
        </label>

        <button style="float:right" class="favorite styled" type="button" id="search_PR" onclick="myFunction()">
            SEARCH Prescription
        </button>
        <script>
            function myFunction() {
                var x = document.getElementById("search_PR");
                x.disabled = true;
            }
        </script>
    </form>

    <div class="doctor_detail_view">
        <table border="1" id="comments">
            <thead>
                <tr>
                    <th>Date&<br>Time</th>
                    <th>Doctor's<br>Full Name</th>
                    <th>Patient's<br>Full Name</th>
                    <th>Patient's<br>SSN</th>
                    <th>Series&<br>Number</th>
                    <th>Diagnostic<br>Code</th>
                    <th>Diagnostic<br>Type</th>
                    <th>Insurance</th>
                    <th>Active<br>Substance</th>
                    <th>Drug Ph.Form</th>
                    <th>Conc.</th>
                    <th>Picked-up?</th>
                </tr>
            </thead>

            {% for prescription in prescriptions %}
                <tr>
                    <td>{{ prescription.created_at }}</td>
                    <td>{{ prescription.doctor.user.last_name }} {{ prescription.doctor.user.first_name }}</td>
                    <td>{{ prescription.patient.user.last_name }} {{ prescription.patient.user.first_name }}</td>
                    <td>{{ prescription.patient.ssn }}</td>
                    <td>{{ prescription.series }} {{ prescription.number }}</td>
                    <td>{{ prescription.prescription_type.diagnostic_code }}</td>
                    <td>{{ prescription.consultation.diagnostic_type.diag_type }}</td>
                    <td>{{ prescription.patient.insurance.name }}</td>
                    <td>{{ prescription.active_substance.active_substance }}</td>
                    <td>{{ prescription.pharmaceutical_form.pharmaceutical_form }}</td>
                    <td>{{ prescription.concentration.concentration }}</td>
{#                    <td>{{ prescription.patient.prescriptionpickup_set.pharmacy.name}}</td>  {# NU SCOATE NIMIC . . #}
                    <td>{{ prescription.patient.prescriptionpickup.pharmacy.name}}</td>        {# NU SCOATE NIMIC . . #}
                </tr>
            {% endfor %}
        </table>
    </div>
    <br>
    <div>
        <a href="{% url 'doctor_new_prescription' %}">Create a NEW PRESCRIPTION</a>
    </div>

    <p>
        {% if object.user != None and object.user != '' %}
        {% else %}The USER you are looking for is not yet created . . .
        {% endif %}
    </p>
    <br>  <br/>
{% endblock %}